export { batchingUpdate, type CdeebeeValueList, type CdeebeeValueItem } from './utils/batchingUpdate';
export type * from './core/types';
export { createCdeebee } from './core/createCdeebee';
export { defaultNormalize, isListEnvelope, extractResultIDList, type CdeebeeListEnvelope } from './core/normalize';
export type { FetchContext } from './core/fetchClient';
export { CdeebeeRequestError, isAbortError } from './core/requestError';
export { shallowEqual } from './utils/shallowEqual';
export { history, type CdeebeeHistoryPlugin, type CdeebeeHistoryState, type CdeebeeHistoryEntry, type CdeebeeHistoryError, type CdeebeeHistoryOptions } from './plugins/history';
export { cancelation, type CdeebeeCancelationOptions } from './plugins/cancelation';
export { queryQueue, type CdeebeeQueryQueueOptions } from './plugins/queryQueue';
export { retry, type CdeebeeRetryOptions } from './plugins/retry';
export { devtools, type CdeebeeDevtoolsOptions } from './plugins/devtools';
